name: icarus
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.6.0+7

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.14
  flutter_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  file_picker: ^9.0.0
  uuid: ^4.5.1
  dash_painter: ^1.0.2
  window_manager: ^0.4.3
  url_launcher: ^6.3.1
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  path: ^1.9.1
  provider: ^6.1.4
  path_provider: ^2.1.5
  desktop_drop: ^0.6.0
  cross_file: ^0.3.4+2
  image: ^4.5.4
  http: ^1.4.0
  custom_mouse_cursor: ^1.1.3
  
 
      
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_ce_generator:  ^1.8.2
  # riverpod_generator: ^2.6.4
  build_runner: ^2.4.14
  json_serializable: ^6.9.3
  riverpod_generator: ^2.6.3
  flutter_lints: ^3.0.0
  msix: ^3.16.8
  # dart run msix:create

msix_config:
  display_name: 'Icarus: Valorant Strategies & Line ups'
  publisher_display_name: Dara A
  identity_name: DaraA.IcarusValorantStrategiesLineups
  publisher: CN=39055448-F6AA-42E9-91F6-9CF8828C444C
  logo_path: E:\Projects\icarus\windows\runner\resources\app_icon.ico
  msix_version: 1.6.0.0
  store: true

flutter:
  fonts:
   - family: CustomIcons
     fonts:
      - asset: assets/fonts/CustomIcons.ttf
  assets:
    - assets/
    - assets/maps/
    - assets/maps/thumbnails/
    - assets/agents/
    - assets/agents/Omen/
    - assets/agents/Killjoy/
    - assets/agents/Sova/
    - assets/agents/Skye/
    - assets/agents/Phoenix/
    - assets/agents/Fade/
    - assets/agents/Yoru/
    - assets/agents/Chamber/
    - assets/agents/Cypher/
    - assets/agents/Raze/
    - assets/agents/Brimstone/
    - assets/agents/Jett/
    - assets/agents/Reyna/
    - assets/agents/Viper/
    - assets/agents/Neon/
    - assets/agents/Astra/
    - assets/agents/Kayo/
    - assets/agents/Breach/
    - assets/agents/Sage/
    - assets/agents/Clove/
    - assets/agents/Iso/
    - assets/agents/Tejo/
    - assets/agents/Vyse/
    - assets/agents/Deadlock/
    - assets/agents/Gekko/
    - assets/agents/Harbor/
    - assets/agents/Waylay/

  uses-material-design: true

 