name: icarus
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.14
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  assets:
    - assets/maps/
    - assets/agents/Omen/
    - assets/agents/Killjoy/
    - assets/agents/Sova/
    - assets/agents/Skye/
    - assets/agents/Phoenix/
    - assets/agents/Fade/
    - assets/agents/Yoru/
    - assets/agents/Chamber/
    - assets/agents/Cypher/
    - assets/agents/Raze/
    - assets/agents/Brimstone/
    - assets/agents/Jett/
    - assets/agents/Reyna/
    - assets/agents/Viper/
    - assets/agents/Neon/
    - assets/agents/Astra/
    - assets/agents/Kayo/
    - assets/agents/Breach/
    - assets/agents/Sage/

  uses-material-design: true

 