// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCloQfAZVQwNhMaYJUc9WuvXRuVGkIBEbQ',
    appId: '1:109851197209:web:c118f4f172729b649b4f88',
    messagingSenderId: '109851197209',
    projectId: 'icarus-hackathon',
    authDomain: 'icarus-hackathon.firebaseapp.com',
    storageBucket: 'icarus-hackathon.firebasestorage.app',
    measurementId: 'G-WH94R53B0D',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3F7fcAHnUO-HGaDWam65cLEWKDNKdOt0',
    appId: '1:109851197209:ios:28131eb235441a589b4f88',
    messagingSenderId: '109851197209',
    projectId: 'icarus-hackathon',
    storageBucket: 'icarus-hackathon.firebasestorage.app',
    iosBundleId: 'com.example.icarus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCloQfAZVQwNhMaYJUc9WuvXRuVGkIBEbQ',
    appId: '1:109851197209:web:8efa188b0bad9ea19b4f88',
    messagingSenderId: '109851197209',
    projectId: 'icarus-hackathon',
    authDomain: 'icarus-hackathon.firebaseapp.com',
    storageBucket: 'icarus-hackathon.firebasestorage.app',
    measurementId: 'G-3B1MLEVEFN',
  );

}