import json,hashlib,gzip
from pathlib import Path
import numpy as np
from PIL import Image,ImageDraw,ImageFont
from tactical_alignment_composite import IndexedTriangles
R=Path('E:/IcarusWorldAudit/2026-09-06/tactical-visibility-revision');D=R/'tower-v14-region-traces';F=R/'tower-contact-v14';m=json.loads((F/'manifest.json').read_text());w=json.loads(gzip.decompress(Path(m['displayWarpFile']).read_bytes()));s=np.array(w['sourceNativeMeters']).reshape(-1,2);t=np.array(w['targetAttackSvg']).reshape(-1,2);indices=np.array(w['triangles']).reshape(-1,3);tri=IndexedTriangles(s,indices);font=ImageFont.truetype('C:/Windows/Fonts/segoeui.ttf',14)
images=[]
for id in ['short99-frontage','97-short99-join','92-raised-profile']:
 r=next(x for x in m['cases'] if x['id']==id and x['side']=='attack');p=np.array(r['query'][:2]);i=tri.find_simplex(p[None])[0];tr=tri.transform[i];u=tr[:2]@(p-tr[2]);o=np.r_[u,1-u.sum()]@t[indices[i]];box=(300*8,140*8,386*8,242*8);im=Image.open(F/f'attack-{id}-8x-overlay.png').convert('RGB').crop(box);d=ImageDraw.Draw(im);px=o*8-[box[0],box[1]];d.line((px[0]-7,px[1],px[0]+7,px[1]),fill='white',width=1);d.line((px[0],px[1]-7,px[0],px[1]+7),fill='white',width=1);d.text((px[0]+9,px[1]-16),'Origin',font=font,fill='white');path=D/f'attack-{id}-context-origin-native8x.png';im.save(path);images.append(dict(path=str(path),sha256=hashlib.sha256(path.read_bytes()).hexdigest(),originSvg=o.tolist(),sourceQuery=r['query'],sourceImage=str(F/f'attack-{id}-8x-overlay.png')))
inputs=[F/'manifest.json',R/'split-wall-family-normalized-candidate-v14/split.height.bin.gz',R/'split-wall-family-normalized-candidate-v14/correspondence.npz',R/'split-wall-family-normalized-candidate-v14/normalized-face-provenance.npz',R/'global-ground-complete-v2/split/correspondence.npz',R/'full-height-input-v1/split/source-correspondence.npz',R.parent/'supplemented-v2/world/split/geometry.json',R.parent/'supplemented-v2/world/split/geometry.npz',Path(m['displayWarpFile']),Path('assets/maps/split_map.svg')]
(D/'evidence-bindings.json').write_text(json.dumps(dict(scope='Bounded sampled ray/source ownership diagnostic. Native first-hit and exact piecewise-affine W crossings; no gameplay or exhaustive all-ray acceptance.',inputs=[dict(path=str(p),sha256=hashlib.sha256(p.read_bytes()).hexdigest()) for p in inputs],annotatedImages=images),indent=2));print('wrote bindings and',len(images),'origin context images')
