"""Review source door/arch inserts backing openings in the connected walls."""
import gzip,json
from pathlib import Path
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d.art3d import Poly3DCollection
from native_compact_wall_profiles import sha
ROOT=Path('E:/IcarusWorldAudit/2026-09-06');REV=ROOT/'tactical-visibility-revision';OUT=REV/'ascent-connected-corner-review-v1'
raw_path=ROOT/'supplemented-v2/world/ascent/geometry.npz';raw=np.load(raw_path);points,faces=raw['points'],raw['faces'];meta=json.loads(raw_path.with_suffix('.json').read_text());affine=np.array(json.loads((ROOT/'tactical-alignment-sides-v1/ascent.json').read_text())['nativeToAttackSvg']);matrix,origin=affine[:,:2],affine[:,2];proposal=json.loads((OUT/'connected-proposals.json').read_text());families={f['edge']:f for c in proposal['chains'] for f in c['families']};coverage=json.loads(gzip.decompress((REV/'all-map-wall-span-coverage-v1/ascent/attack.coverage.json.gz').read_bytes()));rows=[]
for span,obj in [(142,6374),(212,6896)]:
    item=meta['objects'][obj];ids=np.arange(item['firstFace'],item['firstFace']+item['faceCount']);xyz=points[faces[ids]];svg=xyz.copy();svg[:,:,:2]=svg[:,:,:2]@matrix.T+origin;f=families[span];o,t,n=[np.array(f['sourceFrame'][k]) for k in ['origin','tangent','normal']];along=(svg[:,:,:2]-o)@t;depth=(svg[:,:,:2]-o)@n;scale=f['targetAlong'][1]/f['sourceAlong'][1];samples=[r for r in coverage['samples'] if r['span']==span and r.get('sourceObjectIndex')==obj and r.get('probeStartInsideReceiver')];seed_ids=sorted({r['originalSourceFace'] for r in samples});seed=np.isin(ids,seed_ids);outside=(along.max(1)<0)|(along.min(1)>f['sourceAlong'][1]);normal=np.cross(xyz[:,1]-xyz[:,0],xyz[:,2]-xyz[:,0]);normal/=np.maximum(np.linalg.norm(normal,axis=1)[:,None],1e-30)
    row=dict(span=span,sourceObjectIndex=obj,sourceObject=item,sourceFaceIds=ids.tolist(),sourceTrianglesNative=xyz.tolist(),sourceTrianglesSvgZ=svg.tolist(),sourceDepthBoundsSvg=[float(depth.min()),float(depth.max())],sourceAlongBounds=[float(along.min()),float(along.max())],originalHeightBounds=[float(xyz[:,:,2].min()),float(xyz[:,:,2].max())],sourceFacesEntirelyBeyondFamily=ids[outside].tolist(),standingFirstHitFaces=sorted({r['originalSourceFace'] for r in samples if r['relativeEyeHeightMeters']==1.75}),allHeightFirstHitFaces=seed_ids,sourceSamples=samples,proposedDisposition='Distinct structural insert review candidate within the primary wall opening. Preserve original height/UV/material and outside fragments; no opaque fill or state assumption.',normalPolicy='All exact source facets inventoried, including handles/caps/relief. Main-facing plane seeds remain separate from facet-role approval.')
    rows.append(row)
    fig=plt.figure(figsize=(14,6));ax=fig.add_subplot(121);view=fig.add_subplot(122,projection='3d')
    for fragment in f['originalHeightFragments']:
        q=np.array(fragment['targetAlongZ']);ax.fill(q[:,0],q[:,1],color='#0077b6',alpha=.13)
    for i,triangle in enumerate(svg):
        q=np.column_stack((along[i]*scale,triangle[:,2]));ax.fill(q[:,0],q[:,1],color='#f4a261',alpha=.16);ax.plot(*np.vstack((q,q[:1])).T,color='#c46a00',alpha=.35,lw=.3)
    view.add_collection3d(Poly3DCollection(xyz,facecolor='#f4a261',edgecolor='#9c4a00',alpha=.18,linewidth=.25));view.add_collection3d(Poly3DCollection(xyz[seed],facecolor='#e63946',alpha=.35));lo=xyz.min((0,1));hi=xyz.max((0,1));view.set_xlim(lo[0],hi[0]);view.set_ylim(lo[1],hi[1]);view.set_zlim(lo[2],hi[2]);view.set_box_aspect(np.maximum(hi-lo,.1));view.view_init(elev=25,azim=-50);view.set_xlabel('Native X');view.set_ylabel('Native Y');view.set_zlabel('Original Z, m');ax.set_title('Primary wall blue; separate source insert orange');ax.set_xlabel('Proposed authored along, SVG');ax.set_ylabel('Original source Z, m');ax.grid(alpha=.2);view.set_title('Original insert mesh; contact source faces red');fig.suptitle(f"Ascent {span}: {item['path'].split('/')[1]}. Review only; source opacity/state not inferred from the silhouette.");fig.tight_layout(rect=[0,0,1,.94]);fig.savefig(OUT/f'span-{span}-insert-source-review.png',dpi=180);plt.close(fig)
report=dict(scope=__doc__,sourceGeometrySha256=meta['geometrySha256'],sourceFileSha256=sha(raw_path),connectedProposalSha256=sha(OUT/'connected-proposals.json'),scriptSha256=sha(Path(__file__)),inserts=rows,productionMutation=False);(OUT/'insert-proposals.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps([{k:r[k] for k in ['span','sourceObjectIndex','sourceDepthBoundsSvg','sourceAlongBounds','originalHeightBounds','sourceFacesEntirelyBeyondFamily','standingFirstHitFaces']} for r in rows],indent=2))
